
import java.awt.Font;
import javax.swing.JOptionPane;


public class TicTacToe extends javax.swing.JFrame {

    int flag;int drawcheck;
    String Winner;
    public TicTacToe() {
        flag=0; drawcheck=0;
        initComponents();
        jButton1.setText(" ");
        jButton2.setText(" ");
        jButton3.setText(" ");
        jButton4.setText(" ");
        jButton5.setText(" ");
        jButton6.setText(" ");
        jButton7.setText(" ");
        jButton8.setText(" ");
        jButton9.setText(" ");
        Font f=new Font("Aerial",Font.BOLD,75);
        jButton1.setFont(f);
        jButton2.setFont(f);
        jButton3.setFont(f);
        jButton4.setFont(f);
        jButton5.setFont(f);
        jButton6.setFont(f);
        jButton7.setFont(f);
        jButton8.setFont(f);
        jButton9.setFont(f);
        setSize(600, 600);
        setLocationRelativeTo(null);
               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel_2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel_3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel_4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel_5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel_6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel_7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jpanel_8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel_9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 1, 1));

        jPanel_1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_1.setLayout(new java.awt.BorderLayout());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel_1.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_1);

        jPanel_2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_2.setLayout(new java.awt.BorderLayout());

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel_2.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_2);

        jPanel_3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_3.setLayout(new java.awt.BorderLayout());

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel_3.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_3);

        jPanel_4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_4.setLayout(new java.awt.BorderLayout());

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel_4.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_4);

        jPanel_5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_5.setLayout(new java.awt.BorderLayout());

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel_5.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_5);

        jPanel_6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_6.setLayout(new java.awt.BorderLayout());

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel_6.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_6);

        jPanel_7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_7.setLayout(new java.awt.BorderLayout());

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel_7.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_7);

        jpanel_8.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanel_8.setLayout(new java.awt.BorderLayout());

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jpanel_8.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpanel_8);

        jPanel_9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_9.setLayout(new java.awt.BorderLayout());

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel_9.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel_9);

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(flag==0)
        {
            jButton1.setText("X");
            flag=1;
            drawcheck++;
            checker();
            
        }
        else
        {
            jButton1.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
       
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(flag==0)
        {
            jButton2.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton2.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
       
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(flag==0)
        {
            jButton3.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton3.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(flag==0)
        {
            jButton4.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton4.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(flag==0)
        {
            jButton5.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton5.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(flag==0)
        {
            jButton6.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton6.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(flag==0)
        {
            jButton7.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton7.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(flag==0)
        {
            jButton8.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton8.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(flag==0)
        {
            jButton9.setText("X");
            flag=1;drawcheck++;
            checker();
        }
        else
        {
            jButton9.setText("O");
            flag=0;drawcheck++;
            checker();     
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_1;
    private javax.swing.JPanel jPanel_2;
    private javax.swing.JPanel jPanel_3;
    private javax.swing.JPanel jPanel_4;
    private javax.swing.JPanel jPanel_5;
    private javax.swing.JPanel jPanel_6;
    private javax.swing.JPanel jPanel_7;
    private javax.swing.JPanel jPanel_9;
    private javax.swing.JPanel jpanel_8;
    // End of variables declaration                   
 void checker()
{   
    if(drawcheck==9)
    {
        ended("");
    }
    else
    {
  if(jButton1.getText()=="X" && jButton2.getText()=="X" && jButton3.getText()=="X" )
  {
    Winner="Player 1";  ended(Winner);
  }
  else if(jButton1.getText()=="O" && jButton2.getText()=="O" && jButton3.getText()=="O" )
  {
    Winner="Player 2";   ended(Winner);
  }
  
  else if(jButton4.getText()=="X" && jButton5.getText()=="X" && jButton6.getText()=="X")
  {
    Winner="Player 1";   ended(Winner);
  }
  else if(jButton4.getText()=="O" && jButton5.getText()=="O" && jButton6.getText()=="O")
  {
    Winner="Player 2";   ended(Winner);
  }
  
  else if(jButton7.getText()=="X" && jButton8.getText()=="X" && jButton9.getText()=="X")
  {
      Winner="Player 1"; ended(Winner);
  }
  else if(jButton7.getText()=="O" && jButton8.getText()=="O" && jButton9.getText()=="O")
  {
      Winner="Player 2"; ended(Winner);
  }
  
  else if(jButton1.getText()=="X" && jButton4.getText()=="X" && jButton7.getText()=="X")
  {
      Winner="Player 1"; ended(Winner);
  }
  else if(jButton1.getText()=="O" && jButton4.getText()=="O" && jButton7.getText()=="O")
  {
      Winner="Player 2"; ended(Winner);
  }
  
   else if(jButton2.getText()=="X" && jButton5.getText()=="X" && jButton8.getText()=="X")
  {
      Winner="Player 1"; ended(Winner);
  }
  else if(jButton2.getText()=="O" && jButton5.getText()=="O" && jButton8.getText()=="O")
  {
      Winner="Player 2"; ended(Winner);
  }
  
   else if(jButton3.getText()=="X" && jButton6.getText()=="X" && jButton9.getText()=="X")
  {
      Winner="Player 1"; ended(Winner);
  }
  else if(jButton3.getText()=="O" && jButton6.getText()=="O" && jButton9.getText()=="O")
  {
      Winner="Player 2"; ended(Winner);
  }
  
   else if(jButton1.getText()=="X" && jButton5.getText()=="X" && jButton9.getText()=="X")
  {
      Winner="Player 1"; ended(Winner);
  }
  else if(jButton1.getText()=="O" && jButton5.getText()=="O" && jButton9.getText()=="O")
  {
      Winner="Player 2"; ended(Winner);
  }
  
   else if(jButton3.getText()=="X" && jButton5.getText()=="X" && jButton7.getText()=="X")
  {
      Winner="Player 1"; ended(Winner);
  }
  else if(jButton3.getText()=="O" && jButton5.getText()=="O" && jButton7.getText()=="O")
  {
      Winner="Player 2"; ended(Winner);
  }
  
}
}
 void ended(String s)
 {      if(drawcheck==9)
    {
     s="No One";
    }
     JOptionPane.showMessageDialog(this,"Winner is "+s);
     jButton1.setText(" ");
     jButton2.setText(" ");
     jButton3.setText(" ");
     jButton4.setText(" ");
     jButton5.setText(" ");
     jButton6.setText(" ");
     jButton7.setText(" ");
     jButton8.setText(" ");
     jButton9.setText(" ");
     flag=0;drawcheck=0;
     
     
 }
 
}
